### ISSUE TITLE
Invisible and non-removable markers in Varlamore

### ISSUE THREAD

**Issue by grodan-boll** [Xyriella/Immersive-Ground-Markers#1]
You can't place markers in a lot of the Varlamore areas. Not in Cam Torum or in Blood Moon boss room for example. The marks don't show up visually and they can't be "unmarked" once placed either.

**Comment by Xyriella** [comment]
This is likely the known issue about tile markers not working correctly in instances. This is fixed in the in development versions and will hopefully be out soon. Once further development is done, I will test in Cam Torum and the Perilous moon boss rooms to make sure.

**Comment by grodan-boll** [comment]
They seemed to work fine for me in Eclipse boss room for some reason though. Don't know if that's relevant or tells you anything about the reason, but thought it was worth mentioning.

**Comment by Xyriella** [comment]
Thanks, I'll keep that in mind as I investigate further.

**Comment by grodan-boll** [comment]
Love the plugin overall though :) Really helps make the game look like the game again and not like some high-tech dance floor. It’s refreshing to see markers that blend seamlessly with the environment, enhancing immersion rather than disrupting it. Great work!

**Comment by Xyriella** [comment]
![image](https://github.com/Xyriella/Immersive-Ground-Markers/assets/147319921/532b1330-82c8-4a06-a6f4-97f3b341958b)
![image](https://github.com/Xyriella/Immersive-Ground-Markers/assets/147319921/3683e06b-73fa-4d2a-8589-34d7f854f7e1)
Props seem to be working correctly in both Cam Torum and the Blood Moon boss room with the unreleased update
